name: Send advisory

on:
  push:
    branches: [main]

concurrency:
  group: send-advisory-main
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  send-modified-files:
    name: Send advisory files created in last hour
    runs-on: ubuntu-latest
    environment:
      name: communication
    steps:
      - name: Checkout docs
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 2

      - name: Setup mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Install dependencies
        run: mise run sync

      - name: Send advisories
        env:
          SENDGRID_API: ${{ secrets.SENDGRID_API }}
        run: uv run python -m wasoc.send_advisory --auto
