name: Send advisory

on:
  push:
    branches: ['main']


env: # sendgrid api token
  SENDGRID_API: ${{ secrets.SENDGRID_API }}

permissions:
  contents: read

jobs:
  send-modified-files:
    name: Send advisory files created in last hour
    runs-on: ubuntu-latest
    environment:
      name: communication
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout docs
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 2
      - name: Setup mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - name: Install dependencies
        run: mise run sync
      - name: Send advisories
        run: uv run python -m wasoc.send_advisory --auto
